Database:
  type: "mysql" # sqlite ou mysql
  sqlite:
    fileName: "database.db"
  mysql:
    address: "localhost:3306"
    username: "root"
    password: ""
    database: "mochiklubkits"

Kits:
  MK:
    permission: mochiklub.kit.mk
    particle: BLOCK_DUST
    effects:
      - "INCREASE_DAMAGE;15;1"
    config:
      range: 10
      line-cross: 5
      damage: 5.0
    itemstack:
      name: "&aKit MK"
      material: REDSTONE_BLOCK
      data: 0
      lore:
        - "&7Clique &fdireito &7para ativar."
        - ""
        - "&eAtivamento:"
        - " &7 - Atacará em área de {range} blocos"
        - " &7 - Receberá força 1 por 15 segundos"
  Emika:
    permission: mochiklub.kit.emika
    particle: BLOCK_DUST
    effects:
      - "SPEED;15;1"
    config:
      reduce-jump: 1.5
      distance: 4
      distance-fly: 1
    itemstack:
      name: "&aKit Emika"
      material: FIREWORK_ROCKET
      data: 0
      lore:
        - "&7Clique &fdireito &7para ativar."
        - ""
        - "&eAtivamento:"
        - " &7 - Lançará você {distance} blocos para frente"
        - " &7 - Receberá velocidade 1 por 15 segundos"
  Lirou:
    permission: mochiklub.kit.lirou
    particle: BLOCK_DUST
    config:
      distance: 10
      line-cross: 5
      reduce-lava: 2
      reduce-fire: 2
      damage-air: 2.0
      damage-fire: 2.0
      damage-water: 2.0
      damage-earth: 2.0
      effects-element:
        AIR: "LEVITATION;15;1"
        FIRE: null
        WATER: "SLOW;15;1"
        EARTH: "BLINDNESS;15;1"
    itemstack:
      name: "&aKit Lirou"
      material: DIAMOND_BLOCK
      data: 0
      lore:
        - "&7Clique &fdireito &7para ativar."
        - ""
        - "&eAtivamento:"
        - " &7 - Benção dos 4 elementos (fogo, água, terra e ar)"
        - " &7 - Receberá menos dano do elemento fogo"
  Ming:
    permission: mochiklub.kit.ming
    particle: BLOCK_DUST
    config:
      distance: 10
      damage: 5.0
      duration: 10
    itemstack:
      name: "&aKit Ming"
      material: NOTE_BLOCK
      data: 0
      lore:
        - "&7Clique &fdireito &7para ativar."
        - ""
        - "&eAtivamento:"
        - " &7 - Jogará todos os jogadores em um raio"
        - " &7   de {distance} blocos para longe e causará dano."
        - " &7 - Permite visualizar vida de jogadores e monstros"
  Haruko:
    name: "Haruko"
    permission: mochiklub.kit.haruko
    particle: BLOCK_DUST
    config:
      attack-distance: 10
      duration-heal: 10
      life: 4
      heal: -1
    itemstack:
      name: "&aKit Haruko"
      material: EMERALD_BLOCK
      data: 0
      lore:
        - "&7Clique &fesquerdo &7para ativar regeneração."
        - "&7Clique &fdireito &7para atacar projétil."
        - ""
        - "&eAtivamento:"
        - " &7 - Permite curar todos a sua volta, incluindo você."
        - " &7 - Recebe +2 corações de vida"
        - " &7 - Ataque a distância via projétil"

Menus:
  Config:
    title: "Escolha sua classe"
    row: 3
  MK:
    name: "&aKit MK"
    material: NETHER_STAR
    slot: 10
    data: 0
    lore:
      - "&7Clique para escolher esse kit"
  Lirou:
    name: "&aKit Lirou"
    material: NETHER_STAR
    data: 0
    slot: 11
    lore:
      - "&7Clique para escolher esse kit"
  Haruko:
    name: "&aKit Haruko"
    material: NETHER_STAR
    data: 0
    slot: 12
    lore:
      - "&7Clique para escolher esse kit"
  Ming:
    name: "&aKit Ming"
    material: NETHER_STAR
    data: 0
    slot: 13
    lore:
      - "&7Clique para escolher esse kit"
  Emika:
    name: "&aKit Emika"
    material: NETHER_STAR
    data: 0
    slot: 14
    lore:
      - "&7Clique para escolher esse kit"
